FROM node:20-alpine
WORKDIR /workspace

COPY package*.json ./
COPY packages/shared/package.json ./packages/shared/
COPY apps/web/package.json ./apps/web/

RUN npm install

COPY packages/shared ./packages/shared
COPY apps/web ./apps/web

WORKDIR /workspace/apps/web
EXPOSE 5173
