services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.prod
    container_name: gather_api
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      PORT: 4000
    ports:
      - '80:4000'
